AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  HostedZone:
    Description: HostedZone to attach the domain to
    Type: String
  HostName:
    Description: Domain name to host the website on
    Type: String
  Environment:
    Description: One of 'dev' or 'prod'
    Type: String
    Default: dev
  WebsiteCertificate:
    Description: Certificate ARN
    Type: String

Resources:
    WebsiteBucket:
        Type: AWS::S3::Bucket
        Properties:
           AccessControl: PublicRead
           BucketName: !Ref HostName
           WebsiteConfiguration:
              ErrorDocument: 404.html
              IndexDocument: index.html

    WebsiteDistribution:
        Type: AWS::CloudFront::Distribution
        Properties:
            DistributionConfig:
                Origins:
                    - Id: only-origin
                      DomainName: !Sub "${WebsiteBucket}.s3-website-${AWS::Region}.amazonaws.com"
                      CustomOriginConfig:
                        HTTPPort: '80'
                        HTTPSPort: '443'
                        OriginProtocolPolicy: http-only
                Enabled: 'true'
                DefaultCacheBehavior:
                    ForwardedValues:
                        QueryString: 'true'
                    TargetOriginId: only-origin
                    ViewerProtocolPolicy: redirect-to-https
                DefaultRootObject: index.html
                ViewerCertificate:
                    AcmCertificateArn: !Ref WebsiteCertificate
                    SslSupportMethod: sni-only

    OriginRecord:
      Type: AWS::Route53::RecordSet
      Properties:
          AliasTarget:
            DNSName: !GetAtt WebsiteDistribution.DomainName
            HostedZoneId: Z2FDTNDATAQYW2
          HostedZoneId: !Ref 'HostedZone'
          Comment: DNS name for doco site.
          Name: !Ref HostName
          Type: A

